//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS_VSLicenseManager.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HS_VSLicenseManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   5C505A59-E312-4B89-9508-E162F8150517,41717607-F34E-432C-A138-A3CFD7E25CDA,4D8CFBCB-2F6A-4AD2-BABF-10E28F6F2C8F과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_KEY {
            get {
                return ResourceManager.GetString("VS_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VS2019과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_KEY_41717607_F34E_432C_A138_A3CFD7E25CDA {
            get {
                return ResourceManager.GetString("VS_REG_KEY_41717607-F34E-432C-A138-A3CFD7E25CDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VS2015과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_KEY_4D8CFBCB_2F6A_4AD2_BABF_10E28F6F2C8F {
            get {
                return ResourceManager.GetString("VS_REG_KEY_4D8CFBCB-2F6A-4AD2-BABF-10E28F6F2C8F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VS2017과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_KEY_5C505A59_E312_4B89_9508_E162F8150517 {
            get {
                return ResourceManager.GetString("VS_REG_KEY_5C505A59-E312-4B89-9508-E162F8150517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   08878과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_SUB_VS2017 {
            get {
                return ResourceManager.GetString("VS_REG_SUB_VS2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Community과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_SUB_VS2017_08878 {
            get {
                return ResourceManager.GetString("VS_REG_SUB_VS2017_08878", resourceCulture);
            }
        }
        
        /// <summary>
        ///   09278과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_SUB_VS2019 {
            get {
                return ResourceManager.GetString("VS_REG_SUB_VS2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Community과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS_REG_SUB_VS2019_09278 {
            get {
                return ResourceManager.GetString("VS_REG_SUB_VS2019_09278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Studio 2013과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS2013_Name {
            get {
                return ResourceManager.GetString("VS2013_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Studio 2015과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS2015_Name {
            get {
                return ResourceManager.GetString("VS2015_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Studio 2017과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS2017_Name {
            get {
                return ResourceManager.GetString("VS2017_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Studio 2019과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VS2019_Name {
            get {
                return ResourceManager.GetString("VS2019_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon VSIcon {
            get {
                object obj = ResourceManager.GetObject("VSIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   VS2017,VS2019과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VSVersion_Version {
            get {
                return ResourceManager.GetString("VSVersion_Version", resourceCulture);
            }
        }
    }
}
